# Generated by Django 5.0 on 2023-12-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_rename_correct_answer_question_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer',
            new_name='user_answer',
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
